apiVersion: apps/v1
kind: Deployment
metadata:
  name: jbnu-pms-app
  namespace: jbnu-pms
spec:
  # replicas: 2 (개발단계에서 t3.small로 사양 조절)
  replicas: 1
  selector:
    matchLabels:
      app: jbnu-pms-app
  template:
    metadata:
      labels:
        app: jbnu-pms-app
    spec:
      containers:
        - name: app
          image: ghcr.io/dodohy25n/jbnu-pms:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: app-secrets
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-service"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            requests:
              # memory: "512Mi" (개발단계에서 t3.small로 사양 조절)
              memory: "256Mi"
              cpu: "250m"
            limits:
              # memory: "1Gi" (개발단계에서 t3.small로 사양 조절)
              memory: "768Mi"
              cpu: "500m"